language: node_js
node_js:
  - "4.2"
addons:
  apt:
	 sources:
	   - ubuntu-toolchain-r-test
	 packages:
	   - g++-4.8
env:
  - NODE_ENV=test
before_script:
  - apt-get install -qq gcc
  - node index.js &
  - node mock.js &
