language: node_js

node_js:
  - "4.2"
  
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.9
    - gcc-4.9
    
env:
  - NODE_ENV=test
  
before_install:
  - $CXX --version
  
before_script:
  - node index.js &
  - node mock.js &
