# @Author: BingWu Yang <detailyang>
# @Date:   2016-03-16T13:58:02+08:00
# @Email:  detailyang@gmail.com
# @Last modified by:   detailyang
# @Last modified time: 2016-03-16T16:38:18+08:00
# @License: The MIT License (MIT)


language: node_js
node_js:
  - "4.2"
env:
  - NODE_ENV=test
before_script:
  - node index.js &
  - node mock.js &
